try:
    a=10/0
except:
    print("some exceptions raised")
else:
    print("no exceptions raised,everything worked perfectly")
finally:
    print("this ia final block")
print("outside try block")




























